### ISSUE TITLE
Puppeteer works but Puppeteer-cluster doesn't - CentOS 7

### ISSUE THREAD

**Issue by majestique** [thomasdondorf/puppeteer-cluster#120]
Latest version on node (10+) puppeteer & puppeteer-cluster.

This is the `puppeteer` code that works:

```
const puppeteer = require('puppeteer');

(async() => {
const browser = await puppeteer.launch({
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
    ]
});
const page = await browser.newPage();
await page.goto('https://example.com');
await page.screenshot({path: 'example.png'});

browser.close();

})();

```

This is the `puppeteer-cluster` code that doesn't work:
```
const { Cluster } = require('puppeteer-cluster');

(async () => {
  const cluster = await Cluster.launch({
    concurrency: Cluster.CONCURRENCY_CONTEXT,
    maxConcurrency: 2,
    headless: true,
        args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
      ]
  });

  await cluster.task(async ({ page, data: url }) => {
    await page.goto(url);
    const screen = await page.screenshot();
    // Store screenshot, do something else
  });

  cluster.queue('http://www.google.com/');
  cluster.queue('http://www.wikipedia.org/');
  // many more pages

  await cluster.idle();
  await cluster.close();
})();
```

The error I'm getting:

```
bash-4.2$ node cluster.js
(node:31739) UnhandledPromiseRejectionWarning: Error: Unable to launch browser, error message: Failed to launch chrome!
[0321/045848.986524:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x55a44ff92f29 base::debug::CollectStackTrace()
#1 0x55a44fef8593 base::debug::StackTrace::StackTrace()
#2 0x55a44ff0cd1e logging::LogMessage::~LogMessage()
#3 0x55a45157590e service_manager::ZygoteHostImpl::Init()
#4 0x55a44fb4e1b7 content::ContentMainRunnerImpl::Initialize()
#5 0x55a44fb80fca service_manager::Main()
#6 0x55a44fb4c791 content::ContentMain()
#7 0x55a4541e8178 headless::(anonymous namespace)::RunContentMain()
#8 0x55a4541e8205 headless::HeadlessBrowserMain()
#9 0x55a44fb7fca3 headless::HeadlessShellMain()
#10 0x55a44dab71ac ChromeMain
#11 0x7f205624e3d5 __libc_start_main
#12 0x55a44dab702a _start

Received signal 6
#0 0x55a44ff92f29 base::debug::CollectStackTrace()
#1 0x55a44fef8593 base::debug::StackTrace::StackTrace()
#2 0x55a44ff92ab1 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f205c3d65d0 <unknown>
#4 0x7f2056262207 __GI_raise
#5 0x7f20562638f8 __GI_abort
#6 0x55a44ff918e5 base::debug::BreakDebugger()
#7 0x55a44ff0cf61 logging::LogMessage::~LogMessage()
#8 0x55a45157590e service_manager::ZygoteHostImpl::Init()
#9 0x55a44fb4e1b7 content::ContentMainRunnerImpl::Initialize()
#10 0x55a44fb80fca service_manager::Main()
#11 0x55a44fb4c791 content::ContentMain()
#12 0x55a4541e8178 headless::(anonymous namespace)::RunContentMain()
#13 0x55a4541e8205 headless::HeadlessBrowserMain()
#14 0x55a44fb7fca3 headless::HeadlessShellMain()
#15 0x55a44dab71ac ChromeMain
#16 0x7f205624e3d5 __libc_start_main
#17 0x55a44dab702a _start
  r8: 0000000000000000  r9: 0000000000000030 r10: 0000000000000008 r11: 0000000000000206
 r12: 00007ffc20a4f068 r13: 0000000000000161 r14: 00007ffc20a4f9d0 r15: 00007ffc20a4f9c8
  di: 0000000000007c06  si: 0000000000007c06  bp: 00007ffc20a4f010  bx: 0000269447472000
  dx: 0000000000000006  ax: 0000000000000000  cx: ffffffffffffffff  sp: 00007ffc20a4eed8
  ip: 00007f2056262207 efl: 0000000000000206 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at Cluster.<anonymous> (/home/node_modules/puppeteer-cluster/dist/Cluster.js:106:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/node_modules/puppeteer-cluster/dist/Cluster.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:31739) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31739) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

I'm not sure what is causing this but this appears to be `puppeteer-cluster` specific. Any help is appreciated, thanks in advance!

**Comment by thomasdondorf** [comment]
You need to put the options for `puppeteer.launch` (`headless`, `args`) in an attribute called `puppeteerOptions` in `cluster.launch`. Checkout the docs for more information: https://github.com/thomasdondorf/puppeteer-cluster#clusterlaunchoptions

**Comment by majestique** [comment]
For future visitors, it looks like this:
`puppeteerOptions: { args: ['--no-sandbox'] },`

Sample code: https://github.com/thomasdondorf/puppeteer-cluster/blob/master/test/Cluster.test.ts

**Comment by JasonhjKim** [comment]
Hey, I tried this method... i seem to still get this same error 
`(node:25734) UnhandledPromiseRejectionWarning: Error: Unable to launch browser, error message: Failed to launch chrome!
[1118/041704.943373:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at Cluster.<anonymous> (/root/Bunnie-tool-box-checker/node_modules/puppeteer-cluster/dist/Cluster.js:106:23)
    at Generator.throw (<anonymous>)
    at rejected (/root/Bunnie-tool-box-checker/node_modules/puppeteer-cluster/dist/Cluster.js:5:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`
