### ISSUE TITLE
Requests already handled error with puppeteer-extra-plugin-adblocker

### ISSUE THREAD

**Issue by vickyrathee** [thomasdondorf/puppeteer-cluster#270]
When I test the puppeteer-cluster with `puppeteer-extra`. It doesn't work with adblocker plugin. I am testing the [screenshot example](https://github.com/thomasdondorf/puppeteer-cluster/blob/master/examples/express-screenshot.js)

```

const puppeteer = require('puppeteer-extra');
const { Cluster } = require('puppeteer-cluster');

const StealthPlugin = require('puppeteer-extra-plugin-stealth');
puppeteer.use(StealthPlugin());

const AdblockerPlugin = require('puppeteer-extra-plugin-adblocker');
puppeteer.use(AdblockerPlugin({ blockTrackers: true }));

const cluster = await Cluster.launch({
        concurrency: Cluster.CONCURRENCY_CONTEXT,
        maxConcurrency: 5,
        monitor: true,
        puppeteer,
        puppeteerOptions: {
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        }
    });

```
Error

```
(node:162092) UnhandledPromiseRejectionWarning: Error: Request is already handled!
    at assert (c:\Users\VR\github\test-nodejs-service\node_modules\puppeteer\lib\helper.js:283:11)
    at Request.continue (c:\Users\VR\github\test-nodejs-service\node_modules\puppeteer\lib\NetworkManager.js:427:5)
    at Request.<anonymous> (c:\Users\VR\github\test-nodejs-service\node_modules\puppeteer\lib\helper.js:112:23)
    at PuppeteerBlocker.onRequest (c:\Users\VR\github\test-nodejs-service\node_modules\@cliqz\adblocker-puppeteer\dist\cjs\adblocker.js:152:33)
    at Page.BlockingContext.onRequest (c:\Users\VR\github\test-nodejs-service\node_modules\@cliqz\adblocker-puppeteer\dist\cjs\adblocker.js:39:47)
    at Page.emit (events.js:215:7)
    at Page.EventEmitter.emit (domain.js:476:20)
    at NetworkManager.<anonymous> (c:\Users\VR\github\test-nodejs-service\node_modules\puppeteer\lib\Page.js:110:68)
    at NetworkManager.emit (events.js:215:7)
    at NetworkManager.EventEmitter.emit (domain.js:476:20)
  -- ASYNC --
    at Request.<anonymous> (c:\Users\VR\github\test-nodejs-service\node_modules\puppeteer\lib\helper.js:111:15)
    at PuppeteerBlocker.onRequest (c:\Users\VR\github\test-nodejs-service\node_modules\@cliqz\adblocker-puppeteer\dist\cjs\adblocker.js:152:33)
    at Page.BlockingContext.onRequest (c:\Users\VR\github\test-nodejs-service\node_modules\@cliqz\adblocker-puppeteer\dist\cjs\adblocker.js:39:47)
    at Page.emit (events.js:215:7)
    at Page.EventEmitter.emit (domain.js:476:20)
    at NetworkManager.<anonymous> (c:\Users\VR\github\test-nodejs-service\node_modules\puppeteer\lib\Page.js:110:68)
    at NetworkManager.emit (events.js:215:7)
    at NetworkManager.EventEmitter.emit (domain.js:476:20)
    at NetworkManager._onRequest (c:\Users\VR\github\test-nodejs-service\node_modules\puppeteer\lib\NetworkManager.js:234:10)
    at NetworkManager._onRequestWillBeSent (c:\Users\VR\github\test-nodejs-service\node_modules\puppeteer\lib\NetworkManager.js:167:14)
(node:162092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 40)
```

**Comment by thomasdondorf** [comment]
I guess the question is better suited in the plugin repository, but maybe the author can give a hint. @berstend Do you have any idea why this could happen?

**Comment by fmacpro** [comment]
My guess would be somthing to do with [setRequestInterception](https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-puppeteer/adblocker.ts#L76)
