### ISSUE TITLE
No error thrown on Target closed

### ISSUE THREAD

**Issue by vickyrathee** [thomasdondorf/puppeteer-cluster#275]
The cluster doesn't throw any error when puppeteer target is closed, also nothing in `taskerror` event.

It just keep queuing the request and then timeout. I caught it using the `unhandledRejection`

```
process.on('unhandledRejection', async (reason, p) => {
  console.error(reason, 'Unhandled Rejection at Promise', p);
});
```

Error

```
Target closed
Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.send (/var/app/current/node_modules/ws/lib/websocket.js:329:19)
    at WebSocketTransport.send (/var/app/current/node_modules/puppeteer/lib/WebSocketTransport.js:60:14)
    at Connection._rawSend (/var/app/current/node_modules/puppeteer/lib/Connection.js:86:21)
    at CDPSession.send (/var/app/current/node_modules/puppeteer/lib/Connection.js:181:33)
    at Page.evaluateOnNewDocument (/var/app/current/node_modules/puppeteer/lib/Page.js:869:24)
    at Page.<anonymous> (/var/app/current/node_modules/puppeteer/lib/helper.js:112:23)
```

**Comment by thomasdondorf** [comment]
That stack trace does not contain `puppeteer-cluster`, only `puppeteer`. Are you sure your code is using `puppeteer-cluster`?

**Comment by vickyrathee** [comment]
No I am using puppeteer-cluster, I couldn't post all stack trace, but this is related to #207
