### ISSUE TITLE
Not working with Firefox firefox nightly

### ISSUE THREAD

**Issue by mpalavrov** [thomasdondorf/puppeteer-cluster#293]
Hello all,

I tried to start **puppeteer-cluster** with **Firefox nightly** using the below:

```
const args = [
    //https://github.com/puppeteer/puppeteer/issues/1159 || https://github.com/puppeteer/puppeteer/issues/3119
    "--disable-setuid-sandbox",
    "--enable-automation",
    "--disable-browser-side-navigation",
    "--test-type",
    "--start-maximized",
    "--disable-extensions",
    "--disable-popup-blocking",
    "--disable-infobars",
    "--disable-dev-shm-usage",
    "--disable-gpu",
    "--no-sandbox",
    "--disable-features=InfiniteSessionRestore",
    "--enable-features=NetworkService"
];

const options = {
    headless: false,
    w3c: true,
    useAutomationExtension: false,
    // executablePath: 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
    executablePath: 'C:/Program Files/Firefox Nightly/firefox.exe',
    product: 'firefox',
    args
    // acceptInsecureCerts: true,
    // ignoreHTTPSErrors: true
};

    const cluster_Genesis = await Cluster.launch({
        concurrency: Cluster.CONCURRENCY_PAGE,
        monitor: false,
        maxConcurrency: 5,
        puppeteerOptions: options,
        timeout: 14400000, // 4 hours
        workerCreationDelay: 500, // 0.5 seconds delay
    });
```

but it is not working. I receive the following error:

```
(node:26400) UnhandledPromiseRejectionWarning: Error: Unable to launch browser, error message: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at Cluster.<anonymous> (D:\Node Server - Web Form\node_modules\puppeteer-cluster\dist\Cluster.js:116:23)
    at Generator.throw (<anonymous>)
    at rejected (D:\Node Server - Web Form\node_modules\puppeteer-cluster\dist\Cluster.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:26400) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26400) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error: EBUSY: resource busy or locked, unlink 'C:\Users\PALAVR~1\AppData\Local\Temp\puppeteer_dev_firefox_profile-AhRvQz\content-prefs.sqlite'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'C:\\Users\\USERNAME~1\\AppData\\Local\\Temp\\puppeteer_dev_firefox_profile-AhRvQz\\content-prefs.sqlite'
}
```

The browser is opened anyway, but I can't interact with it using puppeteer-cluster:
![image](https://user-images.githubusercontent.com/33352511/83319856-a2c01b80-a24a-11ea-97bf-a8293cf9a095.png)

I have followed this documentation https://pptr.dev/ to try to integrate it.
![image](https://user-images.githubusercontent.com/33352511/83319886-d9963180-a24a-11ea-96fa-d1c517a68b55.png)

I hope someone knows where the issue is and assist.

Also, the puppeteer-firefox is not supported anymore and I can't install it to my project.
Thank you guys.

**Comment by mpalavrov** [comment]
Hi guys,

I hope someone can assist me here.

The reason I want to try with Firefox is because it is handling the Certificate selection differently than Chrome/Chromium, and I want to try if it will be working in Headless mode to automatically select certificate.

Cheers,
Milen

**Comment by mpalavrov** [comment]
Just for whoever is having this issue. The fix for my troubles are...:

```
/**
 * @name Duck Duck Go search
 */

const puppeteer = require('puppeteer-core');

(async () => {
  const browser = await puppeteer.launch({
	  headless: true,
	  product: 'firefox',
	  args: [
	  '-wait-for-browser'
	  ],
	  executablePath: 'C:/Program Files/Firefox Nightly/firefox.exe',
		userDataDir: 'C:/Users/Milen/Desktop/Puppeteer-Test_Firefox/Profile_FirefoxNightly',
	  });

  const page = await browser.newPage()
  	
  //await page.goto('https://duckduckgo.com/')  
      await page.setViewport({ width: 1920, height: 1080 });
   await page.screenshot({path: 'example.png'});
  await browser.close()
})()
```

There were 2 issues with my code:

1. I was using **Firefox Developers** 🔴 instead of **Firefox Nightly** 🟢 , which seems to be an issue.
2. I have added 
```
	  args: [
	  '-wait-for-browser'
	  ],
```
Which seems to be needed when using Firefox.

Cheers guys, I hope it helps someone.

Closing.

**Comment by mpalavrov** [comment]
Actually, it is still not working using the puppeteer-cluster library. It is working with puppeteer-core (without the puppeteer-cluster) using the above example
@thomasdondorf, can you please check this out. I suspect that there is something missing in the puppeteer-core library, or in my request of course, but can you please try it.

**Comment by mpalavrov** [comment]
The puppeteer launch options I am using are:

```
const options_genesis_firefox = {
    headless: false,
    product: 'firefox',
    args: [
        '-wait-for-browser',
    ],
    executablePath: 'C:/Program Files/Firefox Nightly/firefox.exe',
    userDataDir: 'C:/Users/palavrovm/Downloads/tesrt/Profile_FirefoxNightly',
};
```

When like this, I receive the following error:

```
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at Cluster.<anonymous> (D:\Node Server - Web Form\node_modules\puppeteer-cluster\dist\Cluster.js:117:23)
    at Generator.throw (<anonymous>)
    at rejected (D:\Node Server - Web Form\node_modules\puppeteer-cluster\dist\Cluster.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```


If I am using the same, without the puppeteer-cluster, it is working fine, as already mentioned above and example code provided.

I hope someone assists here.

Cheers,
Milen

**Comment by mpalavrov** [comment]
Update

----
The issue was in my TV, mostly. I have explained it in:
https://github.com/puppeteer/puppeteer/issues/5958
