### ISSUE TITLE
Is possible use headless: false?

### ISSUE THREAD

**Issue by gvojtko** [thomasdondorf/puppeteer-cluster#327]
Hello, i possible use headless: false? I still get the following error:

```
Error: Unable to launch browser, error message: Failed to launch the browser process!
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[183:183:0818/082746.784497:ERROR:browser_main_loop.cc(1468)] Unable to open X display.
Received signal 11 SEGV_MAPERR 000000000000
#0 0x556b64db6399 base::debug::CollectStackTrace()
#1 0x556b64d172a3 base::debug::StackTrace::StackTrace()
#2 0x556b64db5f35 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f2266a450e0 (/lib/x86_64-linux-gnu/libpthread-2.24.so+0x110df)
#4 0x556b677acf38 ChromeBrowserMainExtraPartsViewsLinux::~ChromeBrowserMainExtraPartsViewsLinux()
#5 0x556b6495e140 ChromeBrowserMainParts::~ChromeBrowserMainParts()
#6 0x556b6495dcfe ChromeBrowserMainPartsLinux::~ChromeBrowserMainPartsLinux()
#7 0x556b630571bf content::BrowserMainLoop::~BrowserMainLoop()
#8 0x556b630572ce content::BrowserMainLoop::~BrowserMainLoop()
#9 0x556b6305bc2b content::BrowserMainRunnerImpl::Shutdown()
#10 0x556b6305b738 content::BrowserMainRunnerImpl::~BrowserMainRunnerImpl()
#11 0x556b63056d30 content::BrowserMain()
#12 0x556b648e1796 content::ContentMainRunnerImpl::RunServiceManager()
#13 0x556b648e13c7 content::ContentMainRunnerImpl::Run()
#14 0x556b64942ad1 service_manager::Main()
#15 0x556b648df631 content::ContentMain()
#16 0x556b623355ae ChromeMain
#17 0x7f226049b2e1 __libc_start_main
#18 0x556b623353ea _start
  r8: 0000000000000000  r9: 0000000000000001 r10: 0000000000000002 r11: 00001738d2d288e8
 r12: aaaaaaaaaaaaaaaa r13: 00001738d2ccd4b0 r14: 00001738d2d28938 r15: 00001738d2c40380
  di: 00001738d2d28900  si: 00001738d2d68010  bp: 00007ffe62c107d0  bx: 00001738d2d28900
  dx: 00001738d2d68010  ax: 0000000000000000  cx: fffffffd54a4ee4d  sp: 00007ffe62c107c0
  ip: 0000556b677acf38 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at Cluster.<anonymous> (/home/node/app/node_modules/puppeteer-cluster/dist/Cluster.js:120:27)
    at Generator.throw (<anonymous>)
    at rejected (/home/node/app/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Puppeteer options for cluster. I try use also default executablePath.

```
                puppeteerOptions: {
                    executablePath: '/usr/bin/google-chrome',
                    waitIUntil: 'load',
                    headless: false,
                    args: [
                        '--no-sandbox',
                        '--disable-setuid-sandbox',
                        '--disable-dev-shm-usage',
                        '--disable-gpu'
                    ]
                }
```

**Comment by LeCoupa** [comment]
Yes you can. Here is how I do it:

```javascript
const cluster = await Cluster.launch({
      concurrency: Cluster.CONCURRENCY_CONTEXT,
      maxConcurrency: process.env.PUPPETEER_MAX_CONCURRENCY,
      monitor: true,
      puppeteerOptions: {
        headless: false,
        args: [`--window-size=${1680},${970}`],
      },
    })
```
