### ISSUE TITLE
some wonders about maxConcurrency

### ISSUE THREAD

**Issue by gxlfc** [thomasdondorf/puppeteer-cluster#385]
eg，i set maxConcurrency： 20

1、i wonder what maxConcurrency mean？，it mean 20 chromes？or 20 chrome tabs？
2、i parallel request ，like 100 request，but i get error，so how to fix it~ 

{ Error: Protocol error (Network.getResponseBody): No resource with given identifier found
    at Promise (/home/work/nodejs/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/home/work/nodejs/node_modules/puppeteer/lib/Connection.js:182:12)
    at _contentPromise._bodyLoadedPromise.then (/home/work/nodejs/node_modules/puppeteer/lib/NetworkManager.js:618:45)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at Response.<anonymous> (/home/work/nodejs/node_modules/puppeteer/lib/helper.js:111:15)
    at Response.json (/home/work/nodejs/node_modules/puppeteer/lib/NetworkManager.js:639:32)
    at Response.<anonymous> (/home/work/nodejs/node_modules/puppeteer/lib/helper.js:112:23)
    at exports.passLogin (/home/work/nodejs/app/service/passLogin.js:149:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  message: 'Protocol error (Network.getResponseBody): No resource with given identifier found' }

**Comment by drodriguezIE** [comment]
@gxlfc maxConcurrency means the maximum number of parallel workers executing at any given time, for example if you ser maxConcurrency to 20 but you only have 3 tasks queued, it will open 3 browsers, but if you have 100 tasks queued, it will open 20 and as. soon as 1 or more of them is finished, it will open another browser until all 100 tasks are complete.
