### ISSUE TITLE
Multiple instance open in incognito browser how to open multiple instance in normal browser

### ISSUE THREAD

**Issue by Umerhasan97** [thomasdondorf/puppeteer-cluster#414]
Sir i am open puppeteer cluster in multiple browser instance but thus parallel multiple browser instance open in incognito mode and cookies not shared one instance to another instance how to open browser instance cluster in without incognito and share cookies one instance to another

**Comment by farruhsydykov** [comment]
Almost the same issue, is there any way to open multiple browser instances in normal mode?

**Comment by CarmenLexa** [comment]
@farruhsydykov @Umerhasan97 this is my solution

create file concurrency.js
`
const ConcurrencyImplementation = require('puppeteer-cluster/dist/concurrency/ConcurrencyImplementation');
const BROWSER_TIMEOUT = 5000;

class Normal extends ConcurrencyImplementation.default{

    async init() {}
    async close() {}

    async workerInstance(){

        const options = this.options;
        let chrome = await this.puppeteer.launch(options);
        let page;

        return {
            jobInstance: async () => {

                /*await timeoutExecute(BROWSER_TIMEOUT, (async () => {
                   
                })());*/

                const pages = await chrome.pages();
                page = pages[0];

                return {
                    resources: {
                        page,
                    },

                    close: async () => {
                        //await timeoutExecute(BROWSER_TIMEOUT, page.close());
                        await page.close();
                    },
                };
            },

            close: async () => {
                await chrome.close();
            },

            repair: async () => {
            
                try {
                    // will probably fail, but just in case the repair was not necessary
                    await chrome.close();
                } catch (e) {}

                // just relaunch as there is only one page per browser
                chrome = await this.puppeteer.launch(options);
            },
        };
    }
}

module.exports = Normal
`
`
const currency = require('./concurrency.js');
const cluster = await Cluster.launch({

        concurrency: currency,
        maxConcurrency: 2,
        puppeteer,
 });
`
this should work, by opening a separate browser with a url in the first tab

**Comment by 0xZoomEye** [comment]
> @farruhsydykov @Umerhasan97 this is my solution
> 
> create file concurrency.js ` const ConcurrencyImplementation = require('puppeteer-cluster/dist/concurrency/ConcurrencyImplementation'); const BROWSER_TIMEOUT = 5000;
> 
> class Normal extends ConcurrencyImplementation.default{
> 
> ```
> async init() {}
> async close() {}
> 
> async workerInstance(){
> 
>     const options = this.options;
>     let chrome = await this.puppeteer.launch(options);
>     let page;
> 
>     return {
>         jobInstance: async () => {
> 
>             /*await timeoutExecute(BROWSER_TIMEOUT, (async () => {
>                
>             })());*/
> 
>             const pages = await chrome.pages();
>             page = pages[0];
> 
>             return {
>                 resources: {
>                     page,
>                 },
> 
>                 close: async () => {
>                     //await timeoutExecute(BROWSER_TIMEOUT, page.close());
>                     await page.close();
>                 },
>             };
>         },
> 
>         close: async () => {
>             await chrome.close();
>         },
> 
>         repair: async () => {
>         
>             try {
>                 // will probably fail, but just in case the repair was not necessary
>                 await chrome.close();
>             } catch (e) {}
> 
>             // just relaunch as there is only one page per browser
>             chrome = await this.puppeteer.launch(options);
>         },
>     };
> }
> ```
> 
> }
> 
> module.exports = Normal ` ` const currency = require('./concurrency.js'); const cluster = await Cluster.launch({
> 
> ```
>     concurrency: currency,
>     maxConcurrency: 2,
>     puppeteer,
> ```
> 
> }); ` this should work, by opening a separate browser with a url in the first tab

i got this error as below 

            page.on('error', (err) => {
                 ^

TypeError: Cannot read properties of undefined (reading 'on')
    at Worker.<anonymous> (/home/suntopo/Downloads/test/puppeteer-cluster-master/dist/Worker.js:50:18)
    at Generator.next (<anonymous>)
    at fulfilled (/home/suntopo/Downloads/test/puppeteer-cluster-master/dist/Worker.js:5:58)
