### ISSUE TITLE
ProtocolError: Protocol error (Network.setUserAgentOverride): Target closed.

### ISSUE THREAD

**Issue by L3H0** [thomasdondorf/puppeteer-cluster#434]
Hello,
I have a problem with the cluster, if I go normally with puppeter, all pages are correctly scrapped.
But when I use "cluster" I get this error.
Sometimes it's okay, but many times it throws this error.
Can anyone have the same problem?

```
/mnt/puppeter/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Network.setUserAgentOverride): Target closed.
    at /mnt/puppeter/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (/mnt/puppeter/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16)
    at next (/mnt/puppeter/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:32:41)
    at CDPSession.send (/mnt/puppeter/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:57:18)
    at Plugin.onPageCreated (/mnt/puppeter/node_modules/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.js:180:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Plugin._onTargetCreated (/mnt/puppeter/node_modules/puppeteer-extra-plugin/dist/index.cjs.js:496:21) {
  originalMessage: undefined
}

Node.js v17.2.0
```

Can i retry the cluster queue on this error?

**Comment by thomasdondorf** [comment]
Hard to tell what the problem is without seeing any code.
