### ISSUE TITLE
Bug: No way to handle `UnhandledPromiseRejectionWarning` inside `cluster.work`

### ISSUE THREAD

**Issue by mhassan1** [thomasdondorf/puppeteer-cluster#502]
When the `Promise` returned by `doWork` [here](https://github.com/thomasdondorf/puppeteer-cluster/blob/b5b098aed84b8d2c170b3f9d0ac050f53582df45/src/Cluster.ts#L241) is rejected (e.g. , we end up with an `UnhandledPromiseRejectionWarning`, which we can only deal with using a global `process.on('unhandledRejection', ...)` listener. There should be a better way for consumers to handle this error; maybe `cluster` should emit a `clustererror` event (or an `error` event, since it may be fatal), in this case.

I would be happy to contribute a fix, once we have an approach.

To reproduce:
```js
const { Cluster } = require('puppeteer-cluster')

Cluster.launch({
  puppeteerOptions: {
    args: [
      '--single-process'
    ]
  },
}).then(cluster => {
  cluster.queue(async () => {})
})
```
NOTE: This reproduces on my Mac because the `--single-process` flag prevents Chromium from starting up. YMMV.

Actual output:
```txt
Error: Unable to get browser page
    at Worker.<anonymous> (/puppeteer-cluster/node_modules/puppeteer-cluster/dist/Worker.js:41:31)
    at Generator.next (<anonymous>)
    at fulfilled (/puppeteer-cluster/node_modules/puppeteer-cluster/dist/Worker.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.1

Process finished with exit code 1
```

Expected output:
An `error` event should be emitted by `cluster`

Related: https://github.com/thomasdondorf/puppeteer-cluster/issues/323

**Comment by drizzef** [comment]
im also facing the same issue.

**Comment by zhaow-de** [comment]
I can confirm the symptom. The roor cause seems like at https://github.com/thomasdondorf/puppeteer-cluster/blob/b5b098aed84b8d2c170b3f9d0ac050f53582df45/src/Cluster.ts#L238, the `SetTimeout` made `Cluster.doWork` run in the event loop scheduled as macro tasks. Therefore, any error rejects `Cluster.doWork` does not populate to `Cluster.work` and onward, which leads to the unhandeld rejection warning.

**Comment by yangguangwuwu** [comment]
me too

**Comment by yangguangwuwu** [comment]
throw new Error('Unable to get browser page');
                              ^

Error: Unable to get browser page
    at Worker.<anonymous> (/data/wwwroot/aboutlab/node_modules/puppeteer-cluster/dist/Worker.js:41:31)
    at Generator.next (<anonymous>)
    at fulfilled (/data/wwwroot/aboutlab/node_modules/puppeteer-cluster/dist/Worker.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by yangguangwuwu** [comment]
delete  --single-process     
run  ok 
It is possible that puppeteer-cluster relies on multiple processes of browser instances.
